services:
  - type: web
    name: foundercrm-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://foundercrm-backend.onrender.com/api/v1